name=hexed
version=1.0.0
entry=src/app/Main.mod
m2plus=false
includes=src/app src/ui src/core

[deps]
m2gfx
m2bytes
m2sys

[cc]
extra-c=platform/platform_bridge.c

[cc.feature.MACOS]
extra-c=platform/macos/mac_bridge.m
frameworks=Cocoa